spring.application.name=naming-conversion


#Postgre Driver
server.port=8088

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.datasource.url=jdbc:postgresql://localhost:5432/api_demo?currentSchema=naming_conversion
spring.datasource.username=postgres
spring.datasource.password=123456$
spring.datasource.driver-class-name=org.postgresql.Driver